### ISSUE TITLE
ArrayIndexOutOfBoundsException

### ISSUE THREAD

**Issue by MASSI47** [SamJakob/SpiGUI#1]
Hey i get the following error when i try to use your example code at step 2 (https://github.com/SamJakob/SpiGUI)
`Caused by: java.lang.ArrayIndexOutOfBoundsException: 27
        at java.util.Arrays$ArrayList.set(Unknown Source) ~[?:1.8.0_261]
        at net.minecraft.server.v1_16_R1.NonNullList.set(SourceFile:53) ~[patched_1.16.1.jar:git-Purpur-710]
        at org.bukkit.craftbukkit.v1_16_R1.inventory.CraftInventoryCustom$MinecraftInventory.setItem(CraftInventoryCustom.java:108) ~[patched_1.16.1.jar:git-Purpur-710]
        at org.bukkit.craftbukkit.v1_16_R1.inventory.CraftInventory.setItem(CraftInventory.java:99) ~[patched_1.16.1.jar:git-Purpur-710]
        at com.samjakob.spigui.SGMenu.getInventory(SGMenu.java:659) ~[?:?]`

**Comment by SamJakob** [comment]
What size is the inventory?

**Comment by MASSI47** [comment]
3 rows (should be 26 when i count each slot plus the zero one)

**Comment by SamJakob** [comment]
Yeah the max slot should be index 26 (total of 27 slots).
Are you accessing slot 27?

If not, can you send the code you’re using.

**Comment by MASSI47** [comment]
I'm using your example code. I get the error when i try to open the gui.

![Screenshot_48](https://user-images.githubusercontent.com/70591497/91910159-c746ec00-ecae-11ea-9dcb-bd8acb7e81ee.png)

**Comment by SamJakob** [comment]
Ah I’ll take a look, it might be trying to add the pagination items without needing them.
